### ISSUE TITLE
How to disable Eslint-plugin-weex

### ISSUE THREAD

**Issue by denty** [weex-cli/vscode-weex-lang#1]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version:0.12.6
- VS Code version: 1.26.1

## Problem

How to disable "eslint-plugin-weex" ?
add a switch for disable "eslint-plugin-weex" in weex language configuration

**Comment by GGICE** [comment]
In `weex.weex-lang@0.0.7`  add a config option `weexLang.validation.vue`, you can add in you user config like this
```
"weexLang.validation.vue": false
```
I wonder why you want to  disable "eslint-plugin-weex" .

Thank you for your feedback！
